# Railway deployment configuration
# This file tells Railway how to start your application

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.railway_api:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 30"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
