services:
  - type: web
    name: cucov2-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api_server:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
